name: 'news item post'
description: 'Create a news item based on this build.'
inputs:
  apiKey:  # id of input
    description: 'Darl API key'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'